language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ohnova/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ohnova/react-test npm test

after_success:
  - docker build -t ohnova/multi-client ./client
  - docker build -t ohnova/multi-nginx ./nginx
  - docker build -t ohnova/multi-server ./server
  - docker build -t ohnova/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ohnova/multi-client
  - docker push ohnova/multi-nginx
  - docker push ohnova/multi-server
  - docker push ohnova/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: MultiDocker-env
  bucker_name: elasticbeanstalk-ap-northeast-2-632834813816
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY